### ISSUE TITLE
Problem with AOT compilation

### ISSUE THREAD

**Issue by SMASCO** [DevExpress/devextreme-angular#454]
I am trying to apply AOT compilation based on the instructions here 

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

When I run

"node_modules/.bin/ngc" -p tsconfig-aot.json

I get the following error :

can't resolve module ./nested/export from path/node_modules/devextreme-angular/ui/bar-gauge.d.ts
Error: Cannot read property 'DxoExportModule' of undefined, resolving symbol DxBarGaugeModule in path/node_modules/devextreme-angular/ui/bar-gauge.d.ts, resolving symbol DxBarGaugeModule in path/node_modules/devextreme-angular/ui/bar-gauge.d.ts
    at simplifyInContext (path\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (path\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (path\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (path\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (path\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver._loadNgModuleSummary (path\node_modules\@angular\compiler\bundles\compiler.umd.js:14615:33)
    at path\node_modules\@angular\compiler\bundles\compiler.umd.js:14673:57
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (path\node_modules\@angular\compiler\bundles\compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (path\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
Compilation failed

Any suggestions on what I am doing wrong?

**Comment by GoshaFighten** [comment]
I can't reproduce this issue in my sample project. I've attached it. Please modify my project to reproduce the issue.
[GH454.zip](https://github.com/DevExpress/devextreme-angular/files/1008338/GH454.zip)

**Comment by SMASCO** [comment]
this error has been resolved after installing the latest version of typescript ,,
