### ISSUE TITLE
Problem when installing DevExtreme  to an Existing Angular Project

### ISSUE THREAD

**Issue by Coolha** [DevExpress/devextreme-angular#455]
Version:
"devextreme": "^16.2.6",
"devextreme-angular": "^16.2.6"

How to fix this issue, But when i install with new project its work fine
After i Inspect the webpage show this error:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
'dx-button' is not a known element:
1. If 'dx-button' is an Angular component, then verify that it is part of this module.
2. If 'dx-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" class="btn default" type="submit"><i class="icon-magnifier"></i></button>
                        [ERROR ->]<dx-button text="DevExtreme Button in Angular!"></dx-button>
                      </span>
        "): ng:///MainModule/PhoneBookComponent.html@33:24
Error: Template parse errors:
'dx-button' is not a known element:
1. If 'dx-button' is an Angular component, then verify that it is part of this module.
2. If 'dx-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" class="btn default" type="submit"><i class="icon-magnifier"></i></button>
                        [ERROR ->]<dx-button text="DevExtreme Button in Angular!"></dx-button>
                      </span>
        "): ng:///MainModule/PhoneBookComponent.html@33:24
    at syntaxError (http://localhost:4200/vendor.bundle.js:239559:34) [angular]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:249997:19) [angular]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:263769:39) [angular]
    at http://localhost:4200/vendor.bundle.js:263693:62 [angular]
    at Set.forEach (native) [angular]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:263693:19) [angular]
    at createResult (http://localhost:4200/vendor.bundle.js:263578:19) [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:14596:37) [angular]
    at http://localhost:4200/polyfills.bundle.js:6062:57 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:14587:37) [angular]
    at syntaxError (http://localhost:4200/vendor.bundle.js:239559:34) [angular]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:249997:19) [angular]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:263769:39) [angular]
    at http://localhost:4200/vendor.bundle.js:263693:62 [angular]
    at Set.forEach (native) [angular]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:263693:19) [angular]
    at createResult (http://localhost:4200/vendor.bundle.js:263578:19) [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:14596:37) [angular]
    at http://localhost:4200/polyfills.bundle.js:6062:57 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:14587:37) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6014:31) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:5985:17) [angular]
    at http://localhost:4200/polyfills.bundle.js:6062:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:14587:37) [angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:5895:35) [<root>]
    at <anonymous> [<root>]
defaultErrorLogger @ core.es5.js:1084

Thank you

**Comment by artem-kurchenko** [comment]
Hi,

It looks like you haven't registered our modules inside your application. Please take a look at the following help topic - [Import DevExtreme Modules](https://github.com/DevExpress/devextreme-angular#import-devextreme-modules)

For more detailed assistance, feel free to contact us in our [Support Center](https://www.devexpress.com/support/center/question/create). We'll be happy to help.
