### ISSUE TITLE
Add DevExtreme to Ionic 3.15.1 Application Error

### ISSUE THREAD

**Issue by TyroneLao** [DevExpress/devextreme-angular#595]
##### Module build failed: RangeError: Maximum call stack size exceeded 
   devexteme version: ^17.1.7
    devextreme-angular version: ^17.1.7

> Error: ./node_modules/jszip/lib/index.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.getSourceFileOfNode (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:6700:33)
    at checkGrammarForOmittedArgument (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:46811:37)
    at checkGrammarArguments (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:46821:20)
    at checkCallExpression (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:39834:68)
    at checkExpressionWorker (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:41305:28)
    at checkExpression (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:41257:42)
    at checkExpressionCached (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:41138:38)
    at E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:40197:32
    at traverse (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:7261:28)
    at visitEachNode (E:\Workspace\app\staff\node_modules\typescript\lib\typescript.js:14785:30)
 @ ./node_modules/devextreme/client_exporter/excel_creator.js 10:283-299
 @ ./node_modules/devextreme/client_exporter.js
 @ ./node_modules/devextreme/viz/core/export.js
 @ ./node_modules/devextreme/viz/sparklines/base_sparkline.js
 @ ./node_modules/devextreme/viz/sparklines/bullet.js
 @ ./node_modules/devextreme/viz/bullet.js
 @ ./node_modules/devextreme-angular/ui/bullet.js
 @ ./node_modules/devextreme-angular/index.js
 @ ./src/pages/shop/select-area/select-area.module.ts
 @ ./src/pages/shop/select-area/select-area.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (E:\Workspace\app\staff\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (E:\Workspace\app\staff\node_modules\@ionic\app-scripts\dist\webpack.js:119:28)
    at emitRecords.err (E:\Workspace\app\staff\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (E:\Workspace\app\staff\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (E:\Workspace\app\staff\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (E:\Workspace\app\staff\node_modules\webpack\lib\Compiler.js:368:12)
    at next (E:\Workspace\app\staff\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (E:\Workspace\app\staff\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (E:\Workspace\app\staff\node_modules\tapable\lib\Tapable.js:222:13)

**Comment by GoshaFighten** [comment]
We recently updated the [Using the DevExtreme Angular Integration with Ionic 2](https://github.com/DevExpress/devextreme-angular/blob/master/docs/using-ionic2.md) topic to describe how to add our widgets to an Ionic application. I suggest you follow it. If the new recommendations still don't work for you, modify the attached project to reproduce the issue. If this project reproduces the issue, please elaborate on how you run it.
[GH595.zip](https://github.com/DevExpress/devextreme-angular/files/1489080/GH595.zip)

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
