### ISSUE TITLE
Angular prod builds result in runtime error preventing the app to bootstrap

### ISSUE THREAD

**Issue by wartab** [DevExpress/devextreme-angular#656]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

When building an Angular-CLI project that imports Devextreme components with the `--prod` flag, an error is thrown at runtime that prevents the application from even loading.

```
Uncaught TypeError: Cannot set property 'pointerId' of undefined
    at l (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:2394682)
    at e._fireEvent (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:2394899)
    at e.(anonymous function) [as ctor] (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:1391124)
    at new e (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:1391985)
    at String.<anonymous> (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:1794084)
    at OOoa.e.each (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:1883283)
    at Object.N+e8 (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:1794058)
    at o (http://localhost:4200/inline.5e4e8ffddadcaab70a52.bundle.js:1:408)
    at Object.mLDn (http://localhost:4200/main.1881f003c5889497fc21.bundle.js:1:3801245)
    at o (http://localhost:4200/inline.5e4e8ffddadcaab70a52.bundle.js:1:408)
```

This didn't happen at the beginning of last week. I can reproduce this error in a brand new Angular-CLI project. This does not happen with --aot or no flag. It's only --prod.

Repo that reproduces this error:
https://github.com/wartab/devextreme-prod

**Comment by wartab** [comment]
I have tracked down the circumstances under which this error occurs: This does happen with Angular-CLI 1.6.2 and not 1.6.1. We're going to stick with that version for now.

**Comment by dxvladislavvolkov** [comment]
This problem is related to the new version of angular/cli. For more information, you can see this [issue](https://github.com/angular/angular-cli/issues/8992).

**Comment by dxvladislavvolkov** [comment]
I will close this issue since this problem has been fixed by angular/cli

**Comment by wartab** [comment]
Thank you for reaching out to them! Seems like it works fine again.
